### PR TITLE
make compatible with resque_solo by changing the name of redis_key

### PR DESCRIPTION
**Pull request by pboling**
**2021 Update**

I, @pboling, am the maintainer of this gem, which is now retired, and the still-maintained rewrite, which has been renamed to [`resque-unique_at_runtime`](https://github.com/pboling/resque-unique_at_runtime).

Please head over to https://github.com/pboling/resque-unique_at_runtime :)

I'll eventually make an update to the README here.

If someone else can try out this fork and document any issues they have in switching to it from resque-lonely_job, I'll merge these changes into this gem, and provide a migration path.  I expect it would be pretty simple for most to migrate, but will need community help, as I never used this version, because it wouldn't work for me (at all) without the changes in this PR.

**Original**

I needed this gem to be compatible with [resque_solo](https://github.com/neighborland/resque_solo), which provides runtime uniqueness.  With both gems working side by side I can have runtime and queue-time uniqueness.

I have wrapped this setup in some configuration sugar in a new gem called [resque-unique_by_arity](https://github.com/pboling/resque-unique_by_arity).

Also, if this project isn't "alive" anymore I'd be happy to take it over/maintain it.

### CODE REVIEW

**Comment by wallace** [comment]
Hey @pboling , I'm not actively working on this project and would be happy to transfer it over to you if you'd like. Please let me know if you're still interested.

**Comment by pboling** [comment]
@wallace - yes, definitely interested!  I use this project heavily :)

Would you transfer the repo to me, or add me as an owner of `wallace/resque-lonely_job`?

I *think* this is the command to add me as a gem owner on RubyGems.org.

```
gem owner resque-lonely_job -a peter.boling@gmail.com
```

**Comment by wallace** [comment]
Yes, that's the correct command! I've added you as a collaborator on this repository and as an owner on RubyGems.

I'm happy to do whatever makes the most sense going forward.

**Comment by pboling** [comment]
Great thanks.  I'll work on a new release.

**Comment by wallace** [comment]
@pboling , any reason to keep this PR open? Feel free to re-open if so.

**Comment by pboling** [comment]
@wallace Not really.  I need to work on a migration path, or unification path, or at least documentation of what is going on here, but haven't been able to prioritize.  I will work on it soon.  I will be doing rounds through my projects soon.

**Pull request closed without merging**
